### ISSUE TITLE
Movement picker bug

### ISSUE THREAD

**Issue by amshegarh** [ncblakely/CataclysmEngineTweaks#1]
Movement order picker doesn't follow the cursor correctly (seems to be closer than where it should be; based on the distance offset only increases)
![shota010](https://github.com/ncblakely/CataclysmEngineTweaks/assets/11033958/000a4168-69d7-4a77-90da-fa2bc47dc1cc)

**Comment by SuperSajuuk** [comment]
This happens in HW1 Classic as well. I think this is due to the game being designed only for 4:3 aspect ratios, so using a widescreen res misplaces the cursor and disc positions as its trying to calculate position based on a 4:3 res and not 16:9.

a mod for HW1 called Splendor allegedly fixed this, but that mod has long since vanished into the ether iirc. I’d like this to be fixed, but it is quite minor as you can generally work-around/get used to the misplacement of the disc and cursor, plus zoom levels tend to impact the effect of the misplacement, 👍

**Comment by amshegarh** [comment]
shucks
