### ISSUE TITLE
Mission 10 - siege cannon - crash

### ISSUE THREAD

**Issue by Einarloe** [ncblakely/CataclysmEngineTweaks#5]
Hello there! Thank you for uploading this. 

Given I am using cataclysm_loader
And I am in mission 10
And I have built the siege cannon
And I have fired
I see the ball for a second and the game crashes

When using the regular shortcut it works fine. 
Using ""GOG Games\Homeworld Emergence\cataclysm.exe" /noswddraw /safeGL /disableAVI -window -noborder" in 2560 x 1440.

**Comment by Talthos** [comment]
Using the Siege Cannon seems to cause a crash in Skirmish mode, too.

**Comment by ncblakely** [comment]
Thanks for the report. I'm assuming this doesn't happen at 16 or 32 FPS (UpdateRateShift=0 or 1 in the .ini) even with CET installed?

It's likely related to the effects code if so. I thought I tracked down all of the timing bugs there but there must still be a problem.

If you happen to have a save file that repros it it'd save me some time, otherwise I'll look into it soon.

**Comment by ncblakely** [comment]
Fixed in v0.12.
