### ISSUE TITLE
First launch - garbled output

### ISSUE THREAD

**Issue by ajalberd** [ncblakely/CataclysmEngineTweaks#6]
Installed from GOG, and copied the files into the directory. However, a small probably 800x600 window appears in top left corner showing this:

![image](https://github.com/ncblakely/CataclysmEngineTweaks/assets/20324292/8f068c32-fc2b-4f0c-952c-f92af55e919b)

Anything I can do to fix? Should I use dgvoodoo2 or something else?

**Comment by ncblakely** [comment]
Looks like the game launched in software rendering mode, this also occurs without CET. You should be able to change it to OpenGL or D3D in the video options (it's a little hard to see like that, though).

I was planning to disable the SW renderer when the new resolution picker option is enabled to prevent this sort of thing from happening -- I'll leave this issue open to track that.

**Comment by ajalberd** [comment]
Ah! That worked, but now ingame I seem to get a bunch of flashing lines from Glide, in my native resolution. 

![unknown_2024 06 14-15 48_1](https://github.com/ncblakely/CataclysmEngineTweaks/assets/20324292/48531520-46e6-43d9-a7b1-2d08ac09d4dc)


Ever see this before?

**Comment by ncblakely** [comment]
Unfortunately, I haven't played around much with the nGlide wrapper included in the GoG release. 

Does OpenGL work for you? That seems to be more broadly compatible, apart from some people needing to enable the /safeGL command line (this is now configurable in the CET .ini as well). CET removes the need to set Windows NT4 compatibility mode to use it, so that should in theory work without issue.

**Comment by Talthos** [comment]
> Ah! That worked, but now ingame I seem to get a bunch of flashing lines from Glide, in my native resolution.
> 
> ![unknown_2024 06 14-15 48_1](https://private-user-images.githubusercontent.com/20324292/339887127-48531520-46e6-43d9-a7b1-2d08ac09d4dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODg5NTksIm5iZiI6MTcxODQ4ODY1OSwicGF0aCI6Ii8yMDMyNDI5Mi8zMzk4ODcxMjctNDg1MzE1MjAtNDZlNi00M2Q5LWE3YjEtMmQwOGFjMDlkNGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDIxNTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZDczZjE2MmI3OTljMDIyYzAyNzhmM2Y1Y2M1NzFhMzJkODA4MGE5MTZjMTY1N2Y1ZTc5YmNjMjM1ZjMyMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_nKFVU86ZjA5q3cc-0ArjjO3pdT9E-iPn52gZCI9YU)
> 
> Ever see this before?

I've seen that before. Are you using an AMD GPU?

Try setting `SafeGL=true` in the `CataclysmEngineTweaks.ini` (you may need to grab the latest release for that entry to be visible in the ini file).

**Comment by ajalberd** [comment]
> > Ah! That worked, but now ingame I seem to get a bunch of flashing lines from Glide, in my native resolution.
> > ![unknown_2024 06 14-15 48_1](https://private-user-images.githubusercontent.com/20324292/339887127-48531520-46e6-43d9-a7b1-2d08ac09d4dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0ODg5NTksIm5iZiI6MTcxODQ4ODY1OSwicGF0aCI6Ii8yMDMyNDI5Mi8zMzk4ODcxMjctNDg1MzE1MjAtNDZlNi00M2Q5LWE3YjEtMmQwOGFjMDlkNGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDIxNTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZDczZjE2MmI3OTljMDIyYzAyNzhmM2Y1Y2M1NzFhMzJkODA4MGE5MTZjMTY1N2Y1ZTc5YmNjMjM1ZjMyMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i_nKFVU86ZjA5q3cc-0ArjjO3pdT9E-iPn52gZCI9YU)
> > Ever see this before?
> 
> I've seen that before. Are you using an AMD GPU?
> 
> Try setting `SafeGL=true` in the `CataclysmEngineTweaks.ini` (you may need to grab the latest release for that entry to be visible in the ini file).

Hmm, doesn't work for me. Has anyone tried dgvoodoo2 to use Glide instead?

Edit: Just fixed by copying dgvoodoo2 files and maybe replacing the 3dfxspl2 with ones from dgvoodoo's website also fixed it. Thank you for your help!

**Comment by ncblakely** [comment]
Glad that fixed it. Newest release should prevent auto-selection of software mode now too.

**Comment by SuperSajuuk** [comment]
Just for general awareness on this specific issues: don't use the Glide OpenGL provided by GOG. The reason that one exists in the game is because it was provided by GOG solely to ensure players didn't need the Hardware Acceleration fix to use the native OpenGL, which is the most compatible version; however, the GlideGL version is similarly buggy and too new for the game, causing graphical glitches.

Wherever possible, the OpenGL provided by the game natively (which is listed as just OpenGL) should be used and not 3dfx Glide OpenGL, neither should Software or D3D be used due to graphical bugs.

It may be worth to remove all of the renderer options except for the games' native OpenGL, so that players only play the game with a known-to-work OpenGL version, and not end up in situations where they use bad/non-functioning renderers. The default -- working version -- of OpenGL is located in the \3Dfx\WinNT\ folder thats created in the games' installation folder (the folder contains an opengl32.dll file, in the registry the "deviceToSelect" should generally be set to 1 and the "glToSelect" should just say "opengl32.dll" which will point to the correct versions).

NB: Looking at HW Emergence registry keys stored by GOG.com when its installed, it seems the game is configured to pass /noswddraw and /nogldraw command-line parameters in the background when the EXE is launched, even though those are not given in the shortcut arguments. This might explain the graphical issues with using Software and GlideGL renderers reported above, but obviously the preference should be to not use these renderers anyway.

**Comment by Talthos** [comment]
> The default -- working version -- of OpenGL is located in the \3Dfx\WinNT\ folder thats created in the games' installation folder (the folder contains an opengl32.dll file, in the registry the "deviceToSelect" should generally be set to 1 and the "glToSelect" should just say "opengl32.dll" which will point to the correct versions).

Interestingly enough, when I tried to get the game to use the `opengl32.dll` from that folder directly, it didn't work as expected. Further investigation would seem to indicate that the game is somehow using the 'modern' `opengl32.dll`, which is normally located in `C:\Windows\System32`

**Comment by ajalberd** [comment]
It's weird, a fresh install with the Gog version will crash when I switch video mode to openGL. For me, it only works with dgvoodoo2 dlls in there.
