### ISSUE TITLE
Will there be possible to make Engine Tweaks for HW1classic in the future?

### ISSUE THREAD

**Issue by 251371029** [ncblakely/CataclysmEngineTweaks#8]
EDIT

**Comment by ncblakely** [comment]
Since the source code for HW1 is available, these changes are better implemented in a new build of the game than a .dll-based hack. The [Gardens of Kadesh](https://github.com/GardensOfKadesh/Homeworld) project already implements some of the fixes/improvements made here for Cataclysm, such as the improved update rate.
